# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Nairobi', max_length=120),
        ),
    ]
